// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_array from "rescript/lib/es6/caml_array.js";

function tick(tree) {
  switch (tree.TAG) {
    case "Selector" :
        var children = tree._0;
        var _index = 0;
        while(true) {
          var index = _index;
          if (index >= children.length) {
            return "Fail";
          }
          var childStatus = tick(Caml_array.get(children, index));
          switch (childStatus) {
            case "Success" :
                return "Success";
            case "Fail" :
                _index = index + 1 | 0;
                continue ;
            case "Running" :
                return "Running";
            
          }
        };
    case "Sequence" :
        var children$1 = tree._0;
        var _index$1 = 0;
        while(true) {
          var index$1 = _index$1;
          if (index$1 >= children$1.length) {
            return "Success";
          }
          var childStatus$1 = tick(Caml_array.get(children$1, index$1));
          switch (childStatus$1) {
            case "Success" :
                _index$1 = index$1 + 1 | 0;
                continue ;
            case "Fail" :
                return "Fail";
            case "Running" :
                return "Running";
            
          }
        };
    case "Action" :
        console.log("Exécution de l'action : " + tree._0);
        return "Success";
    
  }
}

export {
  tick ,
}
/* No side effect */
